---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: rocky9
    box: rockylinux/9
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
verifier:
  name: ansible
