---
- name: Prepare
  hosts: all

  tasks:
    - name: Include epel role.
      ansible.builtin.include_role:
        name: palekiwi.epel

    - name: Ensure podman is installed.
      become: true
      ansible.builtin.dnf:
        name: podman
        state: present
